name: Go test
on:
  push: {}
  pull_request:
    types: [ opened, synchronize, reopened ]
permissions:
  contents: read
jobs:
  test:
    uses: netcracker/qubership-core-infra/.github/workflows/go-build-with-sonar.yaml@967be79d91d067ccca541dcdecc952b911fb9e80 # v1.3.0
    with:
      actor: ${{ github.actor }}
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
      go-module-dir: '.'
      kube-version: '1.30.0'
      envtest-version: 'release-0.18'
      install-envtest: true
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
